name: Test

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * 4" # every Thursday

concurrency:
  group: test-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions:
  contents: read

jobs:
  Test:
    uses: solidusio/test-solidus-extension/.github/workflows/test.yml@v1
